=== mehah/Greencode-Framework/src/greencode.dtd
<!-- Greencode DTD -->

<!ELEMENT greencode-config (console, browser, multipart, response, view, viewSession, anti-flood, database?, internationalization?, plugins?)>
<!ELEMENT console EMPTY>
	<!ATTLIST console writeLog ( true | false ) "true" >
	
<!ELEMENT browser EMPTY>
	<!ATTLIST browser consoleDebug ( true | false ) "true" >
	
<!ELEMENT multipart EMPTY>
	<!ATTLIST multipart autodectetion ( true | false ) "false" >
	<!ATTLIST multipart max-request-size CDATA "-1">

<!ELEMENT response EMPTY>
	<!ATTLIST response gzip ( true | false ) "false" >
	
<!ELEMENT view (templates?)>
	<!ATTLIST view bootable ( true | false ) "false" >
	<!ATTLIST view seek-change ( true | false ) "true" >
	<!ATTLIST view use-minified ( true | false ) "true" >	
	<!ATTLIST view charset CDATA #REQUIRED>
	<!ELEMENT templates (file+)>
		<!ELEMENT file EMPTY>
			<!ATTLIST file name CDATA #REQUIRED>
			<!ATTLIST file path CDATA #REQUIRED>
			<!ATTLIST file default CDATA #FIXED "default">
	
<!ELEMENT viewSession EMPTY>
	<!ATTLIST viewSession maxInactiveInterval CDATA #REQUIRED>
	
<!ELEMENT anti-flood (default-max-request)>
<!ELEMENT default-max-request ANY>
<!ELEMENT database (default-config-file, show-query?, drivers)>
	<!ELEMENT default-config-file ANY>
	<!ELEMENT show-query ANY>
	<!ELEMENT drivers ANY>
	
<!ELEMENT internationalization (locale+)>
	<!ELEMENT locale EMPTY>
		<!ATTLIST locale language CDATA #REQUIRED>
		<!ATTLIST locale country CDATA #REQUIRED>
		<!ATTLIST locale file CDATA #REQUIRED>
		<!ATTLIST locale charset CDATA #REQUIRED>
		
<!ELEMENT plugins (plugin+)>
	<!ELEMENT plugin EMPTY>
		<!ATTLIST plugin class CDATA #REQUIRED>

=== mehah/Greencode-Framework/src/greencode.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE greencode SYSTEM "greencode.dtd">
<greencode-config>
	<console writeLog="true" />	
	<browser consoleDebug="false" />	
	
	<multipart autodectetion="false" max-request-size="-1" />
	
	<!-- Contem problemas -->
	<response gzip="false" />

	<!--
		bootable: Cache de página. (True: Na inicialização do servidor / False: Na inicialização da página solicitada.
		seek-change: Cada solicitação feita a página, é verificado se ouve mudanças no arquivo e atualiza o cache.
		
		Para produção, aconselho essas configurações.
		bootable=true
		seek-change=false
	 -->
	<view bootable="false" seek-change="true" charset="utf-8">
		<!-- <template-file>template/template.html</template-file> -->
		<use-minified>false</use-minified>
	</view>
	<anti-flood>
		<default-max-request>5</default-max-request>
	</anti-flood>
	<!--<database>
		<default-config-file>database.config.xml</default-config-file>
		<show-query>true</show-query>	
		<drivers>
			<mysql>com.mysql.jdbc.Driver</mysql>
		</drivers>
	</database>
	<internationalization>
		<locale language="pt" country="BR" file="msg_pt-BR.properties" charset="utf-8"/>
		<locale language="en" country="US" file="msg_en-US.properties" charset="utf-8"/> 
	</internationalization>
	<plugins>
		<plugin class="greencode.sengi.Core" /> 
	</plugins>
	-->
</greencode-config>
